### PR TITLE
Various fixes and improvements

### LINKED ISSUE #2389: Reporting - Connections: owner filter cannot be loaded from template
when saving a report template for connection reporting, the owner filter is not loaded correctly

### LINKED ISSUE #2529: UI modelling - add feedback for forbidden NA placement
@SolidProgramming  - this can be seen when configuring "Common Network Areas" in settings - modelling.
Currently there is no feedback at all.

- [x]  also change value of txt message E9015 from "Interface cannot replace requested one: Wrong type." to "Interface cannot replace requested one: the directions of the interfaces do not match (one is a source interface, the other a destination interface)."
- [x] Add visual indicator for the user with above message

### LINKED ISSUE #2540: C# - completely remove RestSharp.Serializers.SystemTextJson
- this has not been updated since Version="106.15.0" from 2021 and we are not actively using it anyway.
- remove it from all c# sources and .csproj files

### LINKED ISSUE #2553: Modelling - manually added app server does not show if in no NA
- where  should the IP appear if if does not match any network area?
- options: 
  - add artificial NA (NAXX/NA??) where to collect these ip addresses
  - add to Internet NA
  - best option: add special ranges used at customer in customizing python import script (hard-coded)

- [x] Ask for csv file of NA01 from customer @tpurschke

### LINKED ISSUE #2573: FWREZNETZ-593 - Interfaces - Email to owner
Customer Ref: FWREZNETZ-593

- [x] Interface request new Option: Email to main person responsible if owner group is empty or no ownergroup specified
- [x]  Add new default for dropdown

### PR DESCRIPTION
**Pull request by SolidProgramming**
Closes #2529
Closes #2540
Closes #2389
Closes #2553
Closes #2573
Closing NuGet bumps

### CODE REVIEW

**Review by tpurschke — COMMENTED** [review]
when entering settings/modelling I get the error message:
```
2024-10-15T10:40:34.085960+00:00 ubu22 fworch-ui:   ---
2024-10-15T10:40:34.085975+00:00 ubu22 fworch-ui:  Exception thrown:
2024-10-15T10:40:34.086002+00:00 ubu22 fworch-ui:   JsonException
2024-10-15T10:40:34.086014+00:00 ubu22 fworch-ui:  Message:
2024-10-15T10:40:34.086028+00:00 ubu22 fworch-ui:   The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
2024-10-15T10:40:34.086086+00:00 ubu22 fworch-ui:  Stack Trace:
2024-10-15T10:40:34.086098+00:00 ubu22 fworch-ui:   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
2024-10-15T10:40:34.086112+00:00 ubu22 fworch-ui:     at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
2024-10-15T10:40:34.086124+00:00 ubu22 fworch-ui:     at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
2024-10-15T10:40:34.086136+00:00 ubu22 fworch-ui:     at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
2024-10-15T10:40:34.086149+00:00 ubu22 fworch-ui:     at FWO.Ui.Pages.Settings.SettingsModelling.OnInitializedAsync() in /usr/local/fworch/ui/files/FWO.UI/Pages/Settings/SettingsModelling.razor:line 300
2024-10-15T10:40:34.088750+00:00 ubu22 fworch-ui:  FWORCHAlert - source: "ui", userId: "3", title: "Read Config", description: "Error reading or processing Config. . See log for details!", alertCode: "UiError"

```

**Comment by tpurschke** [comment]
still get the same problem with the latest version

```
2024-10-15T18:47:44.319753+02:00 lxma635 fworch-ui:  2024-10-15T18:47:44+02:00 Error - Read Config (MainLayout.razor in line 335), User: admin, Role: admin, Error reading or processing Config.
2024-10-15T18:47:44.320061+02:00 lxma635 fworch-ui:   ---
2024-10-15T18:47:44.320173+02:00 lxma635 fworch-ui:  Exception thrown:
2024-10-15T18:47:44.320253+02:00 lxma635 fworch-ui:   JsonException
2024-10-15T18:47:44.320339+02:00 lxma635 fworch-ui:  Message:
2024-10-15T18:47:44.320431+02:00 lxma635 fworch-ui:   The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
2024-10-15T18:47:44.320541+02:00 lxma635 fworch-ui:  Stack Trace:
2024-10-15T18:47:44.320621+02:00 lxma635 fworch-ui:   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
2024-10-15T18:47:44.320709+02:00 lxma635 fworch-ui:     at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
2024-10-15T18:47:44.320824+02:00 lxma635 fworch-ui:     at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
2024-10-15T18:47:44.321034+02:00 lxma635 fworch-ui:     at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
2024-10-15T18:47:44.321135+02:00 lxma635 fworch-ui:     at FWO.Ui.Pages.Settings.SettingsModelling.OnInitializedAsync() in /usr/local/fworch/ui/files/FWO.UI/Pages/Settings/SettingsModelling.razor:line 300
2024-10-15T18:47:44.326987+02:00 lxma635 fworch-ui:  FWORCHAlert - source: "ui", userId: "4", title: "Read Config", description: "Error reading or processing Config. . See log for details!", alertCode: "UiError"
2024-10-15T18:47:44.327226+02:00 lxma635 fworch-ui:  2024-10-15T18:47:44+02:00 Debug - API call (GraphQlApiConnection.cs in line 129), Sending API call  in role : query getOpenAlerts {  alert (where: {ack_by: {_is_null: true}} order...
2024-10-15T18:47:44.329229+02:00 lxma635 fworch-ui:  2024-10-15T18:47:44+02:00 Debug - API call (GraphQlApiConnection.cs in line 129), Sending API call  in role : mutation addUiLog(  $user: Int!  $severity: Int!  $suspectedCause: ... with variables: {"user":4,"severity":2,"suspectedCause":"Read Conf...
2024-10-15T18:47:44.349990+02:00 lxma635 fworch-ui:  2024-10-15T18:47:44+02:00 Debug - API call (GraphQlApiConnection.cs in line 129), Sending API call  in role : mutation addAlert(  $source: String!  $userId: Int  $title: String... with variables: {"source":"ui","userId":4,"title":"Read Config","d...

```

**Comment by SolidProgramming** [comment]
i tested this with a new install and it worked.

**Comment by SolidProgramming** [comment]
@tpurschke there already is a try catch everywhere in the scheduler

**Review by tpurschke — APPROVED** [review]

**Pull request merged**
