### PR TITLE
Develop - tenant filtering for report

### PR DESCRIPTION
**Pull request by Y4nnikH**
ref #406 

tenant filtering for report view in ui

still need to confirm whether or not this approach is efficient enough

### CODE REVIEW

**Review by tpurschke — COMMENTED** [review]
first functionality tests all succeeded:
- filtering out whole rules, without ips of tenant2
- filtering out one of two sources of a rule
- displaying rules with tenant ip in group

**Review by tpurschke — COMMENTED** [review]
When defining a tenant without tenant_network, no rules are displayed.
Ergo if we want to only restrict a tenant to certain devices but want to do no ip filtering, we need to define tenant_networks "0.0.0.0/0" and "::/0".
Also tested this successfully.

**Comment by Y4nnikH** [comment]
I don't really understand why, but generating a resolved Report now takes significantly more time. Only difference between the normal and the resolved query is using the object, service and user **detail** fragments instead of overview, which (in my opinion) should not make a difference this big. But to summarise:
- fetching rows using a function and reading few fields

can be done in pretty much the same time as without using a function (direct access), while
- fetching rows using a function and reading more fields and relationships

will result in a significantly higher fetching time compared to not using a function.

firefox_nrhaBtGXRg

**Comment by tpurschke** [comment]
when doing a fresh install of the current develop branch in your fork, I get the following error during install:

`    /usr/local/fworch/lib/files/FWO.Report.Filter/Compiler.cs(25,36): error CS7036: There is no argument given that corresponds to the required formal parameter 'filtering' of 'DynGraphqlQuery.GenerateQuery(string, AstNode?, DeviceFilter?, TimeFilter?, ReportType?, bool, bool)' [/usr/local/fworch/lib/files/FWO.Report.Filter/FWO.Report.Filter.csproj]
`

**Comment by Y4nnikH** [comment]
Ah sorry, I shouldn't have pushed my changes to this branch already. Install should work again now, but please switch to the newly created "testing" branch for testing the efficiency when filtering using computed fields with non-reporter and recertifier roles.

**Comment by tpurschke** [comment]
> Ah sorry, I shouldn't have pushed my changes to this branch already. Install should work again now, but please switch to the newly created "testing" branch for testing the efficiency when filtering using computed fields with non-reporter and recertifier roles.

thanks - works now in branch "testing" but simple ResolvedRules report takes 12s for admin user

**Comment by tpurschke** [comment]
sorry - should not have been closed (automatically)

**Comment by tpurschke** [comment]
first tests look very promising - and pretty fast

**Comment by Y4nnikH** [comment]
Should be ready for review. Open issues / next steps are
- Set db permissions so that tenant users cannot access rule data directly (froms/tos/objects)
  - first approach on branch [db-tenant-permissions](https://github.com/Y4nnikH/firewall-orchestrator/tree/db-tenant-permissions)
  - will be more difficult than one would hope
- Add possibility to filter for different tenant id as reporter-viewall (#1855)
  - changes into that direction on branch [simulate-tenant](https://github.com/Y4nnikH/firewall-orchestrator/tree/simulate-tenant), but will likely need different approach

**Review by tpurschke — CHANGES_REQUESTED** [review]
when upgrading from this morning's develop state to the current one, I got the following error:
```

TASK [api : import API metadata via metadata API directly from local file] *****
fatal: [fworch-srv]: FAILED! => changed=false 
  content: '{"code":"unexpected","error":"cannot continue due to inconsistent metadata","internal":[{"definition":{"comment":null,"definition":{"function":{"name":"filter_rule_nwobj_resolveds","schema":"public"},"session_argument":"hasura_session"},"name":"filter_rule_nwobj_resolveds","source":"default","table":{"name":"management","schema":"public"}},"name":"computed_field filter_rule_nwobj_resolveds in table management in source default","reason":"Inconsistent object: in table \"management\": in computed field \"filter_rule_nwobj_resolveds\": function \"filter_rule_nwobj_resolveds\" is overloaded. Overloaded functions are not supported","type":"computed_field"}],"path":"$.args"}'
  content_type: application/json; charset=utf-8
  date: Mon, 07 Nov 2022 18:54:30 GMT
  elapsed: 2
  json:
    code: unexpected
    error: cannot continue due to inconsistent metadata
    internal:
    - definition:
        comment: null
        definition:
          function:
            name: filter_rule_nwobj_resolveds
            schema: public
          session_argument: hasura_session
        name: filter_rule_nwobj_resolveds
        source: default
        table:
          name: management
          schema: public
      name: computed_field filter_rule_nwobj_resolveds in table management in source default
      reason: 'Inconsistent object: in table "management": in computed field "filter_rule_nwobj_resolveds": function "filter_rule_nwobj_resolveds" is overloaded. Overloaded functions are not supported'
      type: computed_field
    path: $.args
  msg: 'Status code was 400 and not [200]: HTTP Error 400: Bad Request'
  redirected: false
  server: Warp/3.3.19
  status: 400
  transfer_encoding: chunked
  url: http://127.0.0.1:8080/v1/metadata

```

**Review by tpurschke — CHANGES_REQUESTED** [review]
a db upgrade file containing

    drop function filter_rule_nwobj_resolveds(management, bigint[], bigint);

should do the job (if you change function parameters, you should delete the old function.

**Comment by tpurschke** [comment]
moved into separate branch

**Pull request closed without merging**
