### PR TITLE
One step closer to distributed install

### PR DESCRIPTION
**Pull request by alf-cactus**
It is still not possible to complete a distributed installation. These changes however bring us one step closer
- tests are only conducted on the host they are designed for
- use ansible copy for remote and synchronize for remote host

Non-distributed install tested successfully

### CODE REVIEW

**Review by tpurschke — COMMENTED** [review]
first upgrade test worked but was 10 times slower than usual. Will make some more tests later:
```
PLAY RECAP ****************************************************************************************************************************************
localhost                  : ok=345  changed=113  unreachable=0    failed=0    skipped=199  rescued=0    ignored=1   


real	92m56.614s
user	9m0.330s
sys	1m56.407s
(ansible-venv) tim@ubu20srv:~/fwo-alf-dev$ 
```

**Review by tpurschke — COMMENTED** [review]
is it really necessary here to revert from synchronize to copy when copying to remote systems? this would slow us down again.

**Comment by alf-cactus** [comment]
In case of local installation you use synchronize, else if you use distributed installation you use copy. This behavior is created with
when: inventory_hostname ==(!=) 'localhost'

synchronize has this limitation:
Currently, synchronize is limited to elevating permissions via passwordless sudo. This is because rsync itself is connecting to the remote machine and rsync doesn’t give us a way to pass sudo credentials in.

That makes it unsuited for distributed installations

**Review by tpurschke — APPROVED** [review]
ok, so we give it a try

**Pull request merged**
