### PR TITLE
CSS fixes

### PR DESCRIPTION
**Pull request by NilsPur**

### CODE REVIEW

**Review by tpurschke — CHANGES_REQUESTED** [review]
for me the compliance matrix is still invisible (after first and also second PR)
tested with Chrome & FF

and this (2nd) PR changes some of the sidebars back to white, which is not a consistent look.

**Comment by NilsPur** [comment]
I could not reproduce the missing compliance matrix

**Comment by NilsPur** [comment]
The sidebars are now reverted back to dark blue and I added some further style improvements

**Review by tpurschke — APPROVED** [review]
fixing compliance matrix next PR

**Pull request merged**
