### PR TITLE
CORS + startup bugfix + installer speedup

### LINKED ISSUE #2213: UI Add support for CORS configuration
Add UI config settings for CORS Policy addition to allow remote reverse proxies in front of UI:

Let's wait with this implementation until we double-checked that we need this config setting.

This string of URIs might be added like this:

in roles/ui/files/FWO.UI/Startup.cs
```csharp
        public void ConfigureServices(IServiceCollection services)
             // CORS services
             services.AddCors(options =>
             {
                 options.AddPolicy("AllowSpecificOrigin", builder =>
                 {
builder.WithOrigins("https://rev-proxy-URI");
                 });
             });
 
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
             // Use the CORS policy defined earlier
             app.UseCors("AllowSpecificOrigin");
```

### LINKED ISSUE #2243: Exception starting UI
Launching UI in my debug environment leads to exception since PR #2229 at

builder.WebHost.UseStaticWebAssets();

Exception has occurred: CLR/System.NotSupportedException
An unhandled exception of type 'System.NotSupportedException' occurred in Microsoft.AspNetCore.dll: 'The web root changed from "C:\Users\achim\OneDrive\Dokumente\FWOrch\firewall-orchestrator-1\roles\ui\files\FWO.UI\wwwroot" to "C:\Users\achim\OneDrive\Dokumente\FWOrch\firewall-orchestrator-1\roles\ui\files\FWO.UI\". Changing the host configuration using WebApplicationBuilder.WebHost is not supported. Use WebApplication.CreateBuilder(WebApplicationOptions) instead.'
   at Microsoft.AspNetCore.Builder.ConfigureWebHostBuilder.ConfigureAppConfiguration(Action`2 configureDelegate)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.UseStaticWebAssets(IWebHostBuilder builder)
   at Program.<Main>$(String[] args) in C:\Users\achim\OneDrive\Dokumente\FWOrch\firewall-orchestrator-1\roles\ui\files\FWO.UI\Program.cs:line 20

(After commenting out this line everything works fine on the first look)

Do I need to install a new package or change something in the configuration?

### PR DESCRIPTION
**Pull request by NilsPur**
closes #2213 
closes #2243

### CODE REVIEW

**Review by abarz722 — APPROVED** [review]

**Review by tpurschke — CHANGES_REQUESTED** [review]
1. upgrade script needs to be formulated as list of tasks instead of playbook:
```yaml
# Add remote_addresses config value to config file 

- name: Read existing config file
  slurp:
    src: "{{ fworch_conf_file }}"
  register: config_file

- name: Parse JSON content
  set_fact:
    json_data: "{{ config_file['content'] | b64decode | from_json | default({}) }}"

- name: Add remote_addresses property if not present
  set_fact:
    json_data: "{{ json_data | combine({'remote_addresses': []}) }}"
  when: "'remote_addresses' not in json_data"

- name: Save updated config to file
  copy:
    content: "{{ json_data | to_nice_json }}"
    dest: "{{ fworch_conf_file }}"
  become: true
```
2. syntax error in resulting config file due to missing ",":
```yaml
{
    "api_hasura_jwt_alg": "RS256",
    "api_uri": "https://localhost:9443/api/v1/graphql",
    "dotnet_mode": "Release",
    "fworch_home": "/usr/local/fworch",
    "middleware_native_uri": "http://127.0.0.1:8880/",
    "middleware_uri": "https://127.0.0.1:8888/",
    "product_version": "7.2.3"
    "remote_addresses": []
}
```

**Comment by NilsPur** [comment]
Fixed

**Review by tpurschke — CHANGES_REQUESTED** [review]
still get an error because the copy is missing a "become" statement:
```
TASK [cleanup : Save updated config to file] ******************************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  checksum: d0b03a8b6ce7b071313489c9128a5a995f0d1c2d
  msg: Destination /usr/local/fworch/etc not writable

PLAY RECAP ****************************************************************************************************************************************************************************************
localhost                  : ok=331  changed=107  unreachable=0    failed=1    skipped=198  rescued=0    ignored=1   

tim@debian-test-minimal:~/firewall-orchestrator-nils$ ls -la /usr/local/fworch/etc
total 28
drwxr-xr-x  4 fworch fworch 4096 Sep 25 18:14 .
drwxrwxr-x 17 fworch fworch 4096 Sep 25 18:20 ..
-rw-r--r--  1 fworch fworch  327 Sep 25 18:14 fworch.json
-rwxr-xr-x  1 fworch fworch 1227 Sep 16 15:04 import.conf
-rw-r--r--  1 fworch fworch  820 Sep 16 14:46 iso.conf
drwxr-xr-x  2 fworch fworch 4096 Sep 25 18:20 ldif
drwx------  2 fworch fworch 4096 Sep 25 18:22 secrets
tim@debian-test-minimal:~/firewall-orchestrator-nils$ 
```

second problem (after fixing first):

```
tim@debian-test-minimal:~/firewall-orchestrator-nils$ cat /usr/local/fworch/etc/fworch.json
{
    "api_hasura_jwt_alg": "RS256",
    "api_uri": "https://localhost:9443/api/v1/graphql",
    "dotnet_mode": "Release",
    "fworch_home": "/usr/local/fworch",
    "middleware_native_uri": "http://127.0.0.1:8880/",
    "middleware_uri": "https://127.0.0.1:8888/",
    "product_version": "{{ product_version }}",
    "remote_addresses": []
}
```
should be fixable by changing:

```
    - name: Modify product_version
      set_fact:
        json_data: "{{ config_file.content | b64decode | from_json | combine({'product_version': '{{ product_version }}'}) }}"
```
to

```
    - name: Modify product_version
      set_fact:
        json_data: "{{ config_file.content | b64decode | from_json | combine({'product_version': {{ product_version }} }) }}"
```

**Review by tpurschke — CHANGES_REQUESTED** [review]
upgrade works fine but I cannot get a clean install to work (tested with ubuntu 22.04).
End up with the following error when testing the mw API:
```

TASK [test : middleware test get jwt valid creds] ******************************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  connection: close
  content: |-
    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html><head>
    <title>503 Service Unavailable</title>
    </head><body>
    <h1>Service Unavailable</h1>
    <p>The server is temporarily unable to service your
    request due to maintenance downtime or capacity
    problems. Please try again later.</p>
    <hr>
    <address>Apache/2.4.52 (Ubuntu) Server at 127.0.0.1 Port 8888</address>
    </body></html>
  content_length: '376'
  content_type: text/html; charset=iso-8859-1
  date: Sat, 30 Sep 2023 20:42:46 GMT
  elapsed: 0
  msg: 'Status code was 503 and not [200]: HTTP Error 503: Service Unavailable'
  redirected: false
  server: Apache/2.4.52 (Ubuntu)
  status: 503
  url: https://127.0.0.1:8888/api/AuthenticationToken/Get/

RUNNING HANDLER [test : delete test user and dir] ***************
```

**Comment by NilsPur** [comment]
The CORS data is read in both modes but if an error occurs it is only thrown in debug mode to prevent the application to crash with an exception. Instead it is logged and the application exits with an error code.

**Comment by tpurschke** [comment]
Ja mei

**Pull request merged**
