### PR TITLE
chrome download for pdf

### PR DESCRIPTION
**Pull request by alf-cactus**
Tested in isolated script
@SolidProgramming If you dont need wkhtml anymore I will delete everything above in the file and rename the file
@SolidProgramming Could you test and tell me if this is what you wanted?
@tpurschke Should I uninstall unzip in cleanup role?

### CODE REVIEW

**Comment by SolidProgramming** [comment]
> Tested in isolated script @SolidProgramming If you dont need wkhtml anymore I will delete everything above in the file and rename the file @SolidProgramming Could you test and tell me if this is what you wanted? @tpurschke Should I uninstall unzip in cleanup role?

Deleting wkhtml will be the next step when everything works fine with the new method.

**Review by tpurschke — COMMENTED** [review]
I guess this will probably not work without installing various dependencies  via ansible (see https://chatgpt.com/share/676578d8-e750-8007-be60-498a7ea3d173)
@SolidProgramming have you successfully tested this manually?

in regard to @alf-cactus 's question: not really necessary to remove unzip later

**Comment by alf-cactus** [comment]
@SolidProgramming I named the directories as you wanted

**Comment by SolidProgramming** [comment]
> @SolidProgramming I named the directories as you wanted

Thanks. Will try that shortly.

**Comment by alf-cactus** [comment]
added chrome headless shell, test successful for me, please try @SolidProgramming

**Review by SolidProgramming — APPROVED** [review]

**Pull request merged**
